[common]
version = 2
features = [
    "crash-if-not-sandboxed",
    "foo",
]
import_std = [
    "fs",
    "env",
    "net",
    "process",
    "unix_sockets",
    "terminate",
]

[sandbox]
kind = "Bubblewrap"

# Restrict access to an entire crate.
[api.res1]
include = [
    "res_1",
]

[api.fs]
no_auto_detect = [
    "crab-3",
]

[api.restrict1]
include = [
    "crab_1::restrict1",
]

[api.terminate]
include = [
    "crab-3::terminate",
]

[pkg.crab-1]
allow_unsafe = true
import = [
    "fs",
]
allow_apis = [
    # Don't include fs permission.
    "env",
    "terminate",
]
build.allow_apis = [
    "net",
]
build.sandbox.allow_network = true
from.test.allow_apis = [
    "unix_sockets",
]

[pkg.crab-2]
allow_apis = [
    "env",
    "fs",
]
build.allow_apis = [
    "process",
]
build.allow_build_instructions = [
    "cargo:rustc-env=*",
    "cargo:rustc-link-*"
]
build.allow_unsafe = true

[pkg.crab-3]
allow_unsafe = true
allow_apis = [
    "crab-1::fs",
    # Code in a file that's generated by build.rs.
    "env",
    "process",
    "restrict1",
    "terminate",
]
build.allow_apis = [
    "fs",
]

[pkg.pmacro-1]
allow_apis = [
    "env",
    "fs",
]
allow_proc_macro = true

[pkg.crab-bin]
allow_apis = [
    "env",
    "fs",
    "res1",
]
allow_unsafe = true
build.sandbox.kind = "Disabled"

[pkg.crab-4]
allow_apis = [
    "env",
    "fs",
    "process",
]
allow_unsafe = true

[pkg.crab-5]
allow_apis = [
]
from.build.allow_apis = [
    "fs",
]

[pkg.shared-1]
allow_unsafe = true
allow_apis = [
    "crab-1::fs",
    "env",
]

[pkg.crab-7]
allow_unsafe = true
allow_apis = [
    "env",
    "fs",
]

[pkg.crab-8]
allow_apis = [
    "fs",
]

[pkg.crab-9]
allow_apis = [
    "env",
]
test.sandbox.bind_writable = [
    "crab-9/scratch"
]
test.sandbox.pass_env = [
    "CRAB_9_CRASH_TEST",
]
test.allow_apis = [
    "env",
    "fs",
    "process",
]

[pkg.crab-10]
allow_unsafe = true
build.allow_apis = [
    "env",
    "fs",
    "process",
]
allow_build_instructions = [
    "cargo:rustc-link-*",
]

[pkg.crab-11]
test.sandbox.kind = "Disabled"
test.allow_apis = [
    "env",
    "fs",
    "terminate",
]
