[package]
name = "cackle"
version = "0.1.0"
edition = "2021"
rust-version = "1.62"
license = "MIT OR Apache-2.0"
description = "A Rust code ACL checker"
readme = "README.md"
repository = "https://github.com/davidlattimore/cackle"

[dependencies]
anyhow = "1.0.33"
clap = { version = "4.2.1", features = [ "derive" ] }
serde = { version = "1.0.136", features = [ "derive", "rc" ] }
toml = "0.7.3"
serde_json = "1.0.95"
cargo_metadata = "0.15.4"
object = "0.31.1"
ar = "0.9.0"
gimli = { version = "0.27.2", default-features = false, features = ["read"] }
rustc-demangle = "0.1.22"
once_cell = "1.17.1"
is-terminal = "0.4.8"
colored = "2.0.0"
rustc-ap-rustc_lexer = "727.0.0"
indoc = "2.0.1"
log = { version = "0.4.19", features = [ "std" ] }
addr2line = { version = "0.20.0", default-features = false, features = [ "std" ] }

toml_edit = { version = "0.19.8", optional = true }
ratatui = { version = "0.22.0", optional = true }
diff = { version = "0.1.13", optional = true }
crossterm = { version = "0.26.1", optional = true }

[features]
default = ["ui"]

# Enable the "ui" subcommand.
ui = ["toml_edit", "ratatui", "diff", "crossterm"]

# Build even on an operating system that isn't yet supported. Enable this feature if you're working
# on porting.
unsupported-os = []

[dev-dependencies]
tempfile = "3.6.0"
