[package]
name = "cackle"
version = "0.0.0"
edition = "2021"
rust-version = "1.62"
license = "MIT OR Apache-2.0"
description = "A Rust code ACL checker"
readme = "README.md"
repository = "https://github.com/davidlattimore/cackle"

[dependencies]
anyhow = "1.0.33"
clap = { version = "4.2.1", features = [ "derive" ] }
serde = { version = "1.0.136", features = [ "derive" ] }
toml = "0.7.3"
serde_json = "1.0.95"
cargo_metadata = "0.15.4"
object = "0.30.3"
ar = "0.9.0"
gimli = "0.27.2"
rustc-demangle = "0.1.22"
once_cell = "1.17.1"
atty = "0.2"
colored = "2.0.0"
toml_edit = "0.19.8"
diff = "0.1.13"
rustc-ap-rustc_lexer = "727.0.0"

[dev-dependencies]
indoc = "2.0.1"

[features]
# Build even on an operating system that isn't yet supported. Enable this feature if you're working
# on porting.
unsupported-os = []
