name: Cackle

# We only run Cackle when our Cargo.lock or cackle.toml are changed. A change to any Rust code could
# cause some new code in one of our dependencies to become reachable where it previously wasn't,
# however this is sufficiently rare that it's worthwhile not worrying about. We'd pick this up later
# when Cackle gets run from our cron workflow anyway.
on:
  push:
    branches: [ '**' ]
    paths:
      - Cargo.lock
      - cackle.toml
  pull_request:
    branches: [ '**' ]
    paths:
      - Cargo.lock
      - cackle.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  cackle:
    name: Cackle check and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: cackle-rs/cackle-action@latest
      # Note, we don't cache the target dir, since it currently wouldn't help. We also don't include
      # the toolchain or the OS in the cache key.
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cackle-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo acl -n
      - run: cargo acl -n test
