name: cackle-cron
on:
  schedule:
    - cron: '36 19 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-D warnings'

jobs:
  # Run cackle after updating to the latest semver-compatible versions of packages. This aims to
  # detect any new permission usage introduced by our dependencies.
  cackle:
    if: github.repository == 'cackle-rs/cackle'
    name: cackle with latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: cackle-rs/cackle-action@latest
      - run: cargo update
      - run: cargo acl -n
      - run: cargo acl -n test

  test-nightly:
    if: github.repository == 'cackle-rs/cackle'
    name: Test Nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      id: rust-toolchain
    - run: sudo apt update && sudo apt install git bubblewrap
    - run: cargo test --profile ci
